package streams;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class Map {
    public static void main(String[] args) {
        ArrayList<String> fruits = new ArrayList<>();
        fruits.add("Mango");
        fruits.add("Apple");
        fruits.add("Banana");
        fruits.add("Grapes");
        fruits.add("Pineapple");
        fruits.add("Papaya");

        System.out.println("List of fruits" + fruits);
        /**Map() Usage**/
        List list = fruits.stream().map(f->f.length()).collect(Collectors.toList());
        System.out.println("List generated by map-" + list);
    }
}
